CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"

# Added RET token
DEFAULT_RET_TOKEN = '<ret>'
DEFAULT_RET_TOKEN_INDEX = 32000

# Added entity CLS token
DEFAULT_ENT_CLS_TOKEN = '<ent_cls>'
DEFAULT_ENT_CLS_TOKEN_INDEX = 32001
